'use strict';
var assert=require('assert');
var fs=require('fs');
var vm=require('vm');
var source=fs.readFileSync('apps/pocket-spatial-audius-catalog.js','utf8');
var sandbox={console:console,encodeURIComponent:encodeURIComponent};
vm.runInNewContext(source,sandbox,{filename:'pocket-spatial-audius-catalog.js'});
var api=sandbox.PocketSpatialAudiusCatalogAPI;
assert(api,'Audius catalog API exported');
assert.strictEqual(api.buildCatalogURL(),'https://api.audius.co/v1/tracks/remixables?limit=50');
assert.strictEqual(api.streamURL('D7KyD'),'https://api.audius.co/v1/tracks/D7KyD/stream');
assert.strictEqual(api.licenseAllowsSpatial({license:'CC BY-NC 4.0'}),true);
assert.strictEqual(api.licenseAllowsSpatial({license:'CC BY-NC-ND 4.0'}),false);
assert.strictEqual(api.licenseAllowsSpatial({license:'All Rights Reserved'}),false);
assert.strictEqual(api.licenseAllowsSpatial({}),true,'remixables endpoint may omit duplicate license metadata');
var raw={id:'D7KyD',title:'Test Track',duration:123,is_streamable:true,license:'CC BY 4.0',permalink:'/artist/test-track',user:{name:'Test Artist'}};
var track=api.normalizeTrack(raw);
assert(track,'valid Audius track normalizes');
assert.strictEqual(track.pageid,'audius:D7KyD');
assert.strictEqual(track.artist,'Test Artist');
assert.strictEqual(track.audio,'https://api.audius.co/v1/tracks/D7KyD/stream');
assert.strictEqual(track.file_page,'https://audius.co/artist/test-track');
assert.strictEqual(track.provider,'Audius');
assert.strictEqual(track.duration,123);
assert.strictEqual(api.normalizeTrack({id:'x',is_streamable:false}),null);
var list=api.normalizedTracks({data:[raw,{id:'bad',license:'All Rights Reserved',is_streamable:true}]});
assert.strictEqual(list.length,1);
assert(api.buildCatalogURL().indexOf('api_key')===-1);
assert(api.buildCatalogURL().indexOf('access_token')===-1);
console.log('Pocket Spatial Audius catalog tests passed.');
