#!/usr/bin/env python3
from pathlib import Path

# Apply only the tested retry-context mutation; the helper is removed before merge.
path = Path(__file__).resolve().parent / "room_expression_quality.py"
text = path.read_text()
old = '''def _escape_stale_context(compact: dict, self_entity: str | None) -> None:\n    \"\"\"Mutate only the next model attempt after a semantic-copy rejection.\"\"\"\n    event = compact.get(\"event\") if isinstance(compact.get(\"event\"), dict) else None\n    speaker = str((event or {}).get(\"speaker\") or \"\").lower()\n\n    if event and speaker not in _AUTONOMOUS:\n        compact[\"context\"] = [event]\n        return\n\n    fresh = _recovery_subject(self_entity)\n    compact[\"event\"] = None\n    compact[\"context\"] = []\n    compact[\"discussion\"] = {\n        \"subject\": fresh,\n        \"focus\": fresh,\n        \"related\": [],\n        \"shared\": [],\n        \"open_questions\": [],\n    }\n    compact.pop(\"intent\", None)\n    compact.pop(\"possible_direction\", None)\n    personality = compact.get(\"personality_context\")\n    if isinstance(personality, dict):\n        personality.pop(\"current\", None)\n'''
new = '''def _escape_stale_context(compact: dict, self_entity: str | None) -> None:\n    \"\"\"Drop stale history on retry without forgetting speech from this beat.\"\"\"\n    event = compact.get(\"event\") if isinstance(compact.get(\"event\"), dict) else None\n    speaker = str((event or {}).get(\"speaker\") or \"\").lower()\n\n    if event and speaker not in _AUTONOMOUS:\n        compact[\"context\"] = [event]\n        return\n\n    # Expression retries reuse the same compact object. If a generic duplicate or\n    # self-repetition rejection cleared this list, later attempts became blind to\n    # already-spoken same-beat turns and could publish the exact echo we had just\n    # tried to prevent. Keep only current-beat autonomous speech; older history is\n    # still discarded, so the retry escapes the stale source without losing its\n    # conversational anti-echo boundary.\n    same_beat = _same_beat_prior_turns(compact)\n    if same_beat:\n        compact[\"context\"] = [dict(item) for item in same_beat]\n        compact[\"event\"] = dict(same_beat[-1])\n        return\n\n    fresh = _recovery_subject(self_entity)\n    compact[\"event\"] = None\n    compact[\"context\"] = []\n    compact[\"discussion\"] = {\n        \"subject\": fresh,\n        \"focus\": fresh,\n        \"related\": [],\n        \"shared\": [],\n        \"open_questions\": [],\n    }\n    compact.pop(\"intent\", None)\n    compact.pop(\"possible_direction\", None)\n    personality = compact.get(\"personality_context\")\n    if isinstance(personality, dict):\n        personality.pop(\"current\", None)\n'''
if old not in text:
    raise SystemExit("retry context anchor missing")
path.write_text(text.replace(old, new, 1))
print("retry same-beat context repair applied")
