name = "emily-olivia-community"
main = "src/index.js"
compatibility_date = "2026-08-31"
workers_dev = true

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "COMMUNITY"
class_name = "Community"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Community"]
